### ISSUE TITLE
Can i use this plugin in 3D game.

### ISSUE THREAD

**Issue by ismailivanov** [AdrienQuillet/godot-yet-another-behavior-tree#11]
Can i use this plugin in 3D game.

**Comment by Earewien** [comment]
Hey hi!

For now, this plugin should not work properly on 3D games since nodes, actor and receiver are all Nose2D. 

I think it's possible to make all those nodes inherits from Node instead, allowing this plugin to be used in a 3D game. 

I can create a branch for that. @ismailgamedev are you interested in testing that feature if I make it available on GitHub ? I'm not a 3D game guru so my tests will be limited :/

**Comment by ismailivanov** [comment]
Yes, I can definitely test it. I need it right now, I'm developing a 3d city building game.

**Comment by Earewien** [comment]
@ismailgamedev nice !
I give it a try tomorrow, I will tag you once the feature is developed and ready to be tested, or if I found a major issue doing it 🥲

In the meantime, if you want to practice plugin usage, you can always test it on 2D nodes or create a 2D node wrapper around your 3D actor node (with a composition for example). This will allow you to create some logic with the actuel plugin version.

**Comment by ismailivanov** [comment]
Thanks I will be on standby. Is this feature will be working with NavigationMesh?

**Comment by Earewien** [comment]
In action or condition nodes, you can use whatever you want so I would say yes 👍 

Be sure to structure your code to keep it simple. That's the only constraint when using behavior trees 🌲

**Comment by ismailivanov** [comment]
Do you have a Discord group. Can you send an invitation, we can communicate more easily from there.

**Comment by Earewien** [comment]
I just created one, you're right it will be better to communicate. 

It's fresh new I will configure it later 

https://discord.gg/2BUQmSbm

**Comment by Earewien** [comment]
Merged in main branch
