### ISSUE TITLE
Add node description in the editor

### ISSUE THREAD

**Issue by Cidragon** [AdrienQuillet/godot-yet-another-behavior-tree#22]
**Problem:**

You're working on your behavior tree and decide to add a new node, but then you're not entirely sure which one fit better to your needs so you alt-tab and go to the README to be sure about your decision because there is no text that help you out.

![image](https://user-images.githubusercontent.com/23007679/216169091-1762a4bf-1fc4-406c-9a1e-ad33b7b7306f.png)

**Solution:**

Add the brief introduction page of each node to the editor.

![image](https://user-images.githubusercontent.com/23007679/216169275-0fe11f17-9c7b-441a-b115-989e47a19e8b.png)

**Comment by Earewien** [comment]
Documentation added for nodes and for exported variables too. 

Thing is, the documentation does not always show up... There are issues openned in Godot Project that talk about it.
See next screenshots : both `BTRoot` and `BTCondition` have documentation, but tree root's one is not showing in editor, don't know why. This behavior is totally random.
![cap1](https://user-images.githubusercontent.com/121614863/216309730-8cb8112f-d338-448e-894c-621fda909d0c.png)
![cap2](https://user-images.githubusercontent.com/121614863/216309736-cd5a0cdf-b8c4-41c2-b556-5fe344ffe12d.png)

I close this issue since documentation is here, I hope Godot Editor related bugs will be soon fixed too 😁
