### ISSUE TITLE
Check for orphan nodes

### ISSUE THREAD

**Issue by Earewien** [AdrienQuillet/godot-yet-another-behavior-tree#26]
Obviously there is a node leak in BT addon since there is a lot of orphan nodes.

Run a test scene in verbose and check orphans. If it's related to BT addon, fix it

**Comment by Cidragon** [comment]
This fix also broke the configuration warnings on BTRoot because you're adding a blackboard to the BTRoot node so you always have at least 1 child and with a BTComposite to function there will be at least 2 nodes.

![image](https://user-images.githubusercontent.com/23007679/224516753-38b46a42-5f90-4023-9d51-de55f492d257.png)


Either increase the check value on ```_check_direct_children_validity()``` from 1 to 2 or add the child to another node (like parent because you need an actor anyway)

![image](https://user-images.githubusercontent.com/23007679/224516712-77f5da25-6f1a-4619-9c6b-78a1bc96193d.png)

**Comment by Earewien** [comment]
@Cidragon it should now be fixed :)
